# Generated by Django 5.2.8 on 2026-08-27 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GymManagementApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=150)),
                ('experience', models.PositiveIntegerField()),
                ('bio', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='trainers/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
